modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://gitlab.com/gofancy/koremods/koremods-modlauncher/-/issues"
[[mods]]
modId="koremods"
version="${file.jarVersion}"
displayName="Koremods"
displayURL="https://gitlab.com/gofancy/koremods"
logoFile="logo.png"
authors="Su5eD"
description="A Kotlin Script bytecode manipulation framework."

[[dependencies.koremods]]
    modId="neoforge"
    type="required"
    versionRange="[20.4, 20.5)"
    ordering="NONE"
    side="BOTH"
[[dependencies.koremods]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4,1.21)"
    ordering="NONE"
    side="BOTH"
