modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="koremods_test"
version="${file.jarVersion}"
displayName="Koremods Game Tests"
authors="Su5eD"
description="Game Testing Koremods"

[[dependencies.koremods_test]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.koremods_test]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20, 1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.koremods_test]]
    modId="koremods"
    mandatory=true
    versionRange="[0.6, 0.7)"
    ordering="NONE"
    side="BOTH"
