modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
[[mods]]
modId="koremods_test"
version="${file.jarVersion}"
displayName="Koremods Game Tests"
authors="Su5eD"
description="Game Testing Koremods"

[[dependencies.koremods_test]]
    modId="neoforge"
    type="required"
    versionRange="[20.4, 20.5)"
    ordering="NONE"
    side="BOTH"
[[dependencies.koremods_test]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.koremods_test]]
    modId="koremods"
    type="required"
    versionRange="[1.0, )"
    ordering="NONE"
    side="BOTH"
